### ISSUE TITLE
question : when do I close the database in the example

### ISSUE THREAD

**Issue by roelof1967** [MangroveTech/koa-mongo#3]
Hello, 

I saw the example on the front-page.
But I wonder where and when I close the database ?

Roelof

**Comment by yorkie** [comment]
I guess the real closing action would be self-managed by the module `generic-pool`, but we `release` the connection in the end of every context at https://github.com/MangroveTech/koa-mongo/blob/master/index.js#L56

**Comment by roelof1967** [comment]
Thanks, 

Then I wonder why this script : 

~~~

var koa = require('koa');
var mongo = require('koa-mongo');
 
var app = koa();
 
app.use(mongo());
app.use(function* (next) {
  var query = {};
	var projection = {'State':1, 'Temperature':1};

	var cursor = db.collection('data').find(query, projection);

	// Sort by state and then by temperature (decreasing)
	cursor.sort([['State',1], ['Temperature',-1]]);

	var state = '';	// initialize to dummy value
	var operator = {'$set':{month_high:true}};

	cursor.each(function(err, doc) {
		if (err) throw err;

		if (doc === null) {
			return db.close();
		} else if (doc.State !== state) {
			// first record for each state is the high temp one
			state = doc.State;

			db.collection('data').update({'_id':doc._id}, operator, function(err, updated) {
				if (err) throw err;
			});
		}
	});
});
app.listen(3000);

~~~

never gets ended.

**Comment by yorkie** [comment]
Could you prints the mongo log? and by the way, you should not call `.close()` by yourself

**Comment by roelof1967** [comment]
sorry, but I cannot find a mongo log. Where schould I find that ?

**Comment by yorkie** [comment]
Yeah, @roelof1967 we get get the last line of the log at MongoDB:

```
[conn5] end connection 127.0.0.1:54041 (0 connections now open)  
```

So the connection is closed, what did you mean by "never ended"?

**Comment by roelof1967** [comment]
I mean with never ended that I see a blinking cursor and nothing more.
I was expecting to see the prompt again.

**Comment by yorkie** [comment]
Oh, that doesn't mean you don't close your mongo connections, because you was starting up a server with koa, so your node instance was waiting for requests, that's why you would see cursor on your terminal, that is correct behavior as you described, so I'm going to close the issue, thanks for your feedback :)
